/**
 * Единая база проектов.
 * Чтобы добавить новый проект, достаточно добавить новый объект в массив.
 */
window.AFFGOLD_PROJECTS = [
  {
    id: 'joycasino',
    slug: 'joycasino',
    lastUpdated: '2026-08-03',
    name: 'JoyCasino',
    logo: 'assets/images/joy-logo.svg',
    rating: 4.9,
    verdict: 'Отлично',
    bonus: '100% + 200 FS',
    promoCode: 'BETGOLDTEAM',
    bonusSubtitle: 'На первый депозит',
    wager: 35,
    bonusTypes: ['welcome', 'freespins'],
    studios: ['Pragmatic Play', 'NetEnt', 'Play\'n GO', 'Microgaming', 'Yggdrasil', 'Evolution'],
    payout: 'instant',
    payoutLabel: 'Моментально',
    url: 'https://1663.brightwhale.co/ru/registration?partner=p1663p6519p5724',
    tags: ['Официальный сайт', 'Лицензия Кюрасао', 'Мобильная версия'],
    description: 'JoyCasino — один из самых известных и надёжных проектов на рынке онлайн-развлечений. Работает с 2012 года и заслужил доверие игроков благодаря удобному интерфейсу и большой библиотеке игр.',
    features: ['Более 2000 игровых автоматов', 'Лицензия Кюрасао', 'Быстрые выплаты', 'Круглосуточная поддержка'],
    scores: { reliability: 5.0, bonuses: 4.9, slots: 4.9, payouts: 4.9, support: 4.8 },
    tabs: {
      bonuses: 'Приветственный пакет включает 100% к первому депозиту и 200 фриспинов. Здесь можно указать вейджер, лимиты и срок действия предложения.',
      slots: 'В каталоге представлены слоты популярных игровых студий, live-раздел и настольные игры.',
      payments: 'Поддерживаются банковские карты, электронные кошельки и криптовалюты. Срок обработки зависит от выбранного способа.'
    },
    payments: ['VISA', 'Mastercard', 'МИР', 'Bitcoin', 'Tether', 'WebMoney']
  },
  {
    id: 'norm',
    slug: 'norm-casino',
    lastUpdated: '2026-08-03',
    name: 'NORM Casino',
    logo: 'assets/images/norm-logo.svg',
    rating: 4.8,
    verdict: 'Отлично',
    bonus: '100% + 300 FS',
    promoCode: 'BETGOLDTEAM',
    bonusSubtitle: 'На первый депозит',
    wager: 35,
    bonusTypes: ['welcome', 'freespins'],
    studios: ['BGaming', 'Pragmatic Play', 'Play\'n GO', 'NetEnt', 'Evolution', 'Spribe'],
    payout: 'hour',
    payoutLabel: 'До 1 часа',
    url: 'https://gonormaffiliates.com/?creative_id=7675&serial=61355509',
    tags: ['Актуальный бонус', 'Мобильная версия', 'Поддержка 24/7'],
    description: 'NORM Casino — современный проект с понятной навигацией, адаптивной версией и стартовым предложением для новых пользователей.',
    features: ['Современный интерфейс', 'Большой выбор слотов', 'Поддержка 24/7', 'Адаптация под мобильные устройства'],
    scores: { reliability: 4.8, bonuses: 4.9, slots: 4.7, payouts: 4.7, support: 4.8 },
    tabs: {
      bonuses: 'Стартовое предложение включает 100% к первому пополнению и 300 фриспинов.',
      slots: 'Доступны игровые автоматы от разных студий и отдельные тематические подборки.',
      payments: 'Пополнение и вывод доступны через популярные платёжные методы.'
    },
    payments: ['VISA', 'Mastercard', 'МИР', 'Bitcoin', 'Tether']
  },
  {
    id: 'apex',
    slug: 'apex',
    lastUpdated: '2026-08-03',
    name: 'APEX',
    logo: 'assets/images/apex-logo.svg',
    rating: 4.7,
    verdict: 'Очень хорошо',
    bonus: '225% + 575 FS',
    promoCode: 'BETGOLDTEAM',
    bonusSubtitle: 'Welcome Pack',
    wager: 35,
    bonusTypes: ['welcome', 'freespins'],
    studios: ['Pragmatic Play', 'NetEnt', 'Play\'n GO', 'BGaming', 'Evolution', 'Hacksaw Gaming'],
    payout: 'day',
    payoutLabel: 'До 24 часов',
    url: 'https://balans-apx11-smart.com/addcjylvk3',
    tags: ['Welcome Pack', 'Много фриспинов', 'Мобильная версия'],
    description: 'APEX предлагает многоуровневый welcome-пакет и современный каталог игр.',
    features: ['Welcome Pack до 225%', 'До 575 фриспинов', 'Удобный каталог', 'Мобильная версия'],
    scores: { reliability: 4.7, bonuses: 4.9, slots: 4.7, payouts: 4.5, support: 4.6 },
    tabs: {
      bonuses: 'Бонусная программа разбита на несколько депозитов и включает проценты и фриспины.',
      slots: 'Каталог содержит популярные слоты и новые релизы.',
      payments: 'Сроки вывода зависят от метода и статуса аккаунта.'
    },
    payments: ['VISA', 'Mastercard', 'МИР', 'Tether']
  },
  {
    id: 'tiger',
    slug: 'tiger',
    lastUpdated: '2026-08-03',
    name: 'TIGER',
    logo: 'assets/images/tiger-logo.svg',
    rating: 4.6,
    verdict: 'Очень хорошо',
    bonus: '225% + 600 FS',
    promoCode: 'BETGOLDTEAM',
    bonusSubtitle: 'На первые депозиты',
    wager: 40,
    bonusTypes: ['welcome', 'freespins'],
    studios: ['NetEnt', 'Pragmatic Play', 'Play\'n GO', 'BGaming', 'Evolution', 'Yggdrasil'],
    payout: 'hour',
    payoutLabel: 'До 1 часа',
    url: 'https://gotgr1.com/tnrgglpzk',
    tags: ['Быстрые выплаты', 'Большой бонус', 'Мобильная версия'],
    description: 'TIGER — проект с ярким оформлением, крупным бонусным пакетом и удобным мобильным интерфейсом.',
    features: ['До 225% к депозитам', 'До 600 фриспинов', 'Быстрый вывод', 'Поддержка 24/7'],
    scores: { reliability: 4.6, bonuses: 4.8, slots: 4.6, payouts: 4.7, support: 4.5 },
    tabs: {
      bonuses: 'Бонусный пакет включает проценты к депозитам и фриспины.',
      slots: 'Доступны слоты, live-игры и тематические подборки.',
      payments: 'Большинство популярных способов пополнения и вывода поддерживается.'
    },
    payments: ['VISA', 'Mastercard', 'Bitcoin', 'Tether']
  },
  {
    id: 'fenix',
    slug: 'fenix',
    lastUpdated: '2026-08-03',
    name: 'FENIX',
    logo: 'assets/images/fenix-logo.svg',
    rating: 4.5,
    verdict: 'Хорошо',
    bonus: '225% + 600 FS',
    promoCode: 'BETGOLDTEAM',
    bonusSubtitle: 'Welcome-предложение',
    wager: 35,
    bonusTypes: ['welcome', 'freespins'],
    studios: ['BGaming', 'Pragmatic Play', 'Play\'n GO', 'NetEnt', 'Evolution', 'Spribe'],
    payout: 'day',
    payoutLabel: 'До 24 часов',
    url: 'https://fnx-abs.net/dqwhllle1',
    tags: ['Welcome-бонус', 'Фриспины', 'Адаптивный сайт'],
    description: 'FENIX — проект с большим welcome-предложением, удобным каталогом и яркой фирменной стилистикой.',
    features: ['До 225% бонуса', 'До 600 фриспинов', 'Игры разных студий', 'Мобильная версия'],
    scores: { reliability: 4.5, bonuses: 4.7, slots: 4.5, payouts: 4.4, support: 4.5 },
    tabs: {
      bonuses: 'Для новых пользователей доступен расширенный бонусный пакет.',
      slots: 'Каталог включает популярные игровые автоматы.',
      payments: 'Доступны банковские карты и электронные способы оплаты.'
    },
    payments: ['VISA', 'Mastercard', 'МИР', 'WebMoney']
  },
  {
    id: 'eva',
    slug: 'eva',
    lastUpdated: '2026-08-03',
    name: 'EVA',
    logo: 'assets/images/eva-logo.svg',
    rating: 4.3,
    verdict: 'Хорошо',
    bonus: '225% + 900 FS',
    promoCode: 'BETGOLDTEAM',
    bonusSubtitle: 'На первые депозиты',
    wager: 30,
    bonusTypes: ['welcome', 'freespins', 'cashback'],
    studios: ['NetEnt', 'Pragmatic Play', 'BGaming', 'Play\'n GO', 'Evolution', 'Hacksaw Gaming'],
    payout: 'instant',
    payoutLabel: 'Моментально',
    url: 'https://string-26eva.com/d3guxsdl2',
    tags: ['До 900 FS', 'Акции', 'Мобильная версия'],
    description: 'EVA выделяется крупным пакетом фриспинов и регулярными акциями для пользователей.',
    features: ['До 225% бонуса', 'До 900 фриспинов', 'Регулярные акции', 'Удобная мобильная версия'],
    scores: { reliability: 4.3, bonuses: 4.7, slots: 4.4, payouts: 4.2, support: 4.3 },
    tabs: {
      bonuses: 'Доступны welcome-бонусы, фриспины и периодические акции.',
      slots: 'Представлены слоты разных жанров и игровых студий.',
      payments: 'Доступны основные банковские и электронные методы.'
    },
    payments: ['VISA', 'Mastercard', 'МИР', 'Bitcoin']
  }
];
